import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   'intro',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
  tutorialSidebar: [
    {
      type: "category",
      label: "Get Started",
      items: [
        "get-started/intro",
        "get-started/landingpage",
        "get-started/mongodb",
        "get-started/userauth",
        "get-started/themes",
        "get-started/claudinary",
      ],
    },
    {
      type: "category",
      label: "Payments - Setup",
      items: [
        "payments/lemonsqueezy",
        "payments/stripe",
        "payments/dodopayments",
      ],
    },
    {
      type: "category",
      label: "Admin - Services",
      items: ["admin/admindashboard",
        "admin/blogmanagement",
        "admin/usermanagement"
      ],
    },
    {
      type: "category",
      label: "AI - Setup",
      items: ["ai-setup/chatgpt", "ai-setup/claude"],
    },
    {
      type: "category",
      label: "Production - Deployment",
      items: ["production/deployment"],
    },
  ],
};

export default sidebars;
